In [2]:
import numpy as np
import matplotlib.pyplot as plt

##### 2차원 배열 슬라이싱 #2

In [ ]:
# 2차원 배열 슬라이싱
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

print(a[1,2])    # 1행 2열의 원소 출력 (8)
print(a[1:2])    # 1행의 원소 출력(콤마 기호 없음 : 행의 모든 원소 선택)
print(a[:, -1])    # 모든 행의 마지막 열 출력
print(a[1:3, 1:4])    # 1~2행, 1~3열 출력

8
[[ 6  7  8  9 10]]
[ 5 10 15 20]
[[ 7  8  9]
 [12 13 14]]


##### 2차원 배열 슬라이싱 #3

In [17]:
#2차원 배열 분리
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

x = data[: , :-1]
y = data[: , -1]
print(f'x={x}')
print(f'y={y}')

x=[[1 2]
 [4 5]
 [7 8]]
y=[3 6 9]


##### 3차원 배열 인덱싱 및 슬라이싱

In [ ]:
arr3d = np.array([[[1,2,3],
                   [4,5,6]],    # 첫번째 면(차원)
                   [[7,8,9],
                    [10,11,12]]])    # 두번째 면(차원)

print(arr3d)

# 첫 번째 면의 첫 번째 행, 열
print(f'arr3d[0,0,0] : {arr3d[0,0,0]}')

# 첫 번째 면의 첫 번째 행의 모든 열
print(f'arr3d[0,0,:] : \n {arr3d[0,0,:]}')    #[앞면, 0행, 전체 열]

# 첫 번째 면의 두 번째 열의 모든 행
print(f'arr3d[0,:,1] : \n {arr3d[0,:,1]}')

# 두 번째 면의 모든 행과 모든 열
print(f'arr3d[1,:,:] : \n {arr3d[1,:,:]}')
print(f'arr3d[1,:] : \n {arr3d[1,:]}')

print('\n')
print('모든 차원의 0번째 행의 모든 열')
print(arr3d[:,0,:])

print('두 번째 차원의 0,1행의 0,1 컬럼')
print(arr3d[1,0:2,0:2])

print('모든 차원의 모든 행의 2번째 열')
print(arr3d[:,:,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
arr3d[0,0,0] : 1
arr3d[0,0,:] : 
 [1 2 3]
arr3d[0,:,1] : 
 [2 5]
arr3d[1,:,:] : 
 [[ 7  8  9]
 [10 11 12]]
arr3d[1,:] : 
 [[ 7  8  9]
 [10 11 12]]


모든 차원의 0번째 행의 모든 열
[[1 2 3]
 [7 8 9]]
두 번째 차원의 0,1행의 0,1 컬럼
[[ 7  8]
 [10 11]]
모든 차원의 모든 행의 2번째 열
[[ 3  6]
 [ 9 12]]


##### Numpy 벡터화 연산

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)    # 동일한 인덱스끼리 덧셈
print(a+2)    # 배열의 각 원소에 2를 더함
print(a*2)    # 배열의 각 원소에 *2 (벡터화 연산)
print(a+10)    # 배열의 각 원소에 +10 (벡터화 연산)

list1 = [1,2,3]

print(list1 * 2)    # 리스트 원소 반복
print(list1 + 2)    # TypeError 발생

[5 7 9]
[3 4 5]
[2 4 6]
[11 12 13]
[1, 2, 3, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

##### Numpy 배열 연산

In [20]:
a = np.array([1,2,3], dtype=np.int32)
b = np.array([4,5,6], dtype=np.int64)

c = a + b
print(c)
print(c.dtype)

[5 7 9]
int64


##### Numpy 배열 연산 : 기본 산술 연산

In [2]:
# 배열 생성
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# 기본 연산(element-wise)
print(f'덧셈 : {a+b}')
print(f'뺄셈 : {a-b}')
print(f'곱셈 : {a*b}')
print(f'나눗셈:{b/a}')

# 스칼라와의 연산
print(f'스칼라 곱 : {a*3}')
print(f'스칼라 더하기 : {a+10}')

덧셈 : [ 6  8 10 12]
뺄셈 : [-4 -4 -4 -4]
곱셈 : [ 5 12 21 32]
나눗셈:[5.         3.         2.33333333 2.        ]
스칼라 곱 : [ 3  6  9 12]
스칼라 더하기 : [11 12 13 14]


##### Numpy 배열 연산 : 비교 연산

In [24]:
# 비교 연산 : 배열간 비교
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,6])

print(f'a와 b 같은 값 : {a == b}')
print(f'a가 b보다 큰 값 : {a > b}')
# 결과 : Bollean 배열

a와 b 같은 값 : [ True False False  True False]
a가 b보다 큰 값 : [False False  True False False]


##### Numpy 배열 연산 : 수학 함수

In [4]:
# 수학 함수들
arr = np.array([1,4,9,16,25])
print(f'제곱근 : {np.sqrt(arr)}')

print(f'로그 : {np.log(arr)}')

print(f'지수 : {np.exp([1,2,3])}')    # [e^1, e^2, e^3]

# 삼각함수
angles = np.array([0,np.pi/2, np.pi])
print(f'sin 값 : {np.sin(angles)}')

print(f'cos 값 : {np.cos(angles)}')

제곱근 : [1. 2. 3. 4. 5.]
로그 : [0.         1.38629436 2.19722458 2.77258872 3.21887582]
지수 : [ 2.71828183  7.3890561  20.08553692]
sin 값 : [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos 값 : [ 1.000000e+00  6.123234e-17 -1.000000e+00]


##### Numpy 배열 연산 : 집계 함수

In [27]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(f'합계 : {np.sum(data)}')
print(f'평균 : {np.mean(data)}')
print(f'최대값 : {np.max(data)}')
print(f'최소값 : {np.min(data)}')
# 위의 넷은 집계함수 => 최종 결과는 1개의 값(축 설정 없음)

# 축(axis) 지정
print(f'각 열의 합 : {np.sum(data, axis=0)}')    # [12 15 18]
print(f'각 행의 합 : {np.sum(data, axis=1)}')    # [ 6 15 24]

합계 : 45
평균 : 5.0
최대값 : 9
최소값 : 1
각 열의 합 : [12 15 18]
각 행의 합 : [ 6 15 24]


##### 2차원 배열의 축(axis) #1

In [6]:
x = np.array([[0,1],
              [2,3],
              [4,5]])

print('axis=None: ', x.sum(axis=None))
print('axis=0: ', x.sum(axis=0), x.sum(axis=0).shape)    # 각 column(열) 합계
print('axis=1: ', x.sum(axis=1), x.sum(axis=1).shape)    # 각 row(행)별 합계

axis=None:  15
axis=0:  [6 9] (2,)
axis=1:  [1 5 9] (3,)


##### 2차원 배열의 축(axis) #2

In [7]:
scores = np.array([[99,93,60],
                   [98,82,93],
                   [93,65,81],
                   [78,82,81]])

mean_col = scores.mean(axis=0)    # col단위 평균
print(mean_col.round(1))

mean_row = scores.mean(axis=1)    # row단위 평균
print(mean_row.round(1))

[92.  80.5 78.8]
[84.  91.  79.7 80.3]


##### 3차원 배열의 축 연산 #1

In [ ]:
#z = np.arange(24).reshape(2,3,4)    # reshape(z축, 행, 열)
z = np.array([[[0,1,2,3],    # 3차원 배열 [0]
               [4,5,6,7],
               [8,9,10,11]],
               [[12,13,14,15],     # 3차원 배열 [1]
                [16,17,18,19],
                [20,21,22,23]]])

print(z.shape)
print(f'z[0]:\n {z[0]}')    # 첫번째 면(차원)
print(f'z[1]:\n {z[1]}')    # 두번째 면

sum_axis0 = np.sum(z, axis=0)    # axis=0 - 2차원 배열(z[0], z[1])의 같은 위치에 있는 요소들을 더함
print('sum(z, axis=0)')    # 동일한 인덱스 원소의 합
print(sum_axis0)

(2, 3, 4)
z[0]:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
z[1]:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
sum(z, axis=0)
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


##### 3차원 배열의 축 연산 #2

In [9]:
sum_axis1 = np.sum(z, axis=1)
print('sum(z, axis=1)')    # 각 컬럼 단위의 합
print(sum_axis1)

sum(z, axis=1)
[[12 15 18 21]
 [48 51 54 57]]


##### 3차원 배열의 축 연산 #3

In [10]:
sum_axis2 = np.sum(z, axis=2)
print('sum(z, axis=2)')    # 각 행 단위의 합
print(sum_axis2)

sum(z, axis=2)
[[ 6 22 38]
 [54 70 86]]


##### 브로드캐스팅(Broadcasting)

In [11]:
a = np.ones((2,3))
b = np.ones((3,2))

print(a+b)    # ValueError 발생 : shape 불일치

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [13]:
# 스칼라와 배열 연산 : 스칼라 자동 확장
arr = np.array([1,2,3])    # arr.shape:(3,)
result = arr + 10

print(result)    # [11 12 13]

# 1차원 배열과 2차원 배열 연산 : 자동 확장
a1 = np.array([[1,3,5],
               [7,9,11]])    # shape : (2,3)
a2 = np.array([2,4,6])    # shape : (3,) -> (1,3)로 간주

print(a1.shape)
print(a2.shape)

result = a1+a2

print(result)

[11 12 13]
(2, 3)
(3,)
[[ 3  7 11]
 [ 9 13 17]]


In [15]:
# 열벡터와 행벡터의 연산
col = np.array([[1], [2], [3]])    # shape (3,1)
row = np.array([10,20,30])    # shape (3,) -> (1,3)
result = col + row
print(result)

# 다차원 배열의 브로드캐스팅
A = np.array([[1,2,3],
              [4,5,6]])    # shape (2,3)
B = np.array([[10], [20]])    # shape (2,1)

result = A + B
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[11 12 13]
 [24 25 26]]


##### 배열 구조 변경 : reshape()

In [21]:
a = np.arange(1,21)    # a.size = 20, 1차원 배열 (1x20)
print(a)

print('4x5 크기 배열')
a = a.reshape(4,5)    # a.size = 20, 2차원 배열 (4x5)
print(a)

print('2x10 크기 배열')
b = a.reshape(2,10)
print(b)

print('?x4 크기 배열')
c = b.reshape(-1, 4)    # 열의 개수(4)에 맞추어 자동으로 생성
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
4x5 크기 배열
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2x10 크기 배열
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
?x4 크기 배열
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


##### 배열 구조 변경 : reshape() 예제

In [22]:
array1 = np.arange(1,11).reshape(2,5)
print(array1)
print()

array2 = array1.reshape(5,2)
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


##### 배열 구조 변경 : 1차원으로 평탄화

In [ ]:
arr2d = np.array([[1,2,3],
                  [4,5,6]])

flat = arr2d.flatten()    # 새로운 배열 생성
print('flatten():', flat)

rav = arr2d.ravel()
print('ravel():', rav)

flat[1] = 100    # flattern으로 만든 배열 수정
print('flattern 수정 후 원본:')
print(arr2d)    # 원본은 변경 안됨

rav[0] = 90    # ravel로 만든 배열 수정
print('ravel 수정 후 원본:')
print(arr2d)    # 원본도 변경됨

flatten(): [1 2 3 4 5 6]
ravel(): [1 2 3 4 5 6]
flattern 수정 후 원본:
[[1 2 3]
 [4 5 6]]
ravel 수정 후 원본:
[[90  2  3]
 [ 4  5  6]]


##### 조건부 데이터 검색

In [ ]:
scores = np.array([85,72,95,68,88,79,92,84,76,90])
names = np.array(['김철수','이영희','박민수','최지연','정우진',
                  '한소희','오준석','윤서연','임동현','송하윤'])

high_scores = scores > 80    # 조건식
print(f'high_scores : {high_scores}')
print('80점 이상인 학생 : ')
print(f'점수 : {scores[high_scores]}')
print(f'이름 : {names[high_scores]}')

# 여러 조건 조합
excellent = (scores >= 90)
print(f'excellent : {excellent}')

failing = scores < 70
print(f'failing : {failing}')

print(f'\n 우수 학생 ({np.sum(excellent)}명):')
print(f'이름 : {names[excellent]}')
print(f'점수 : {scores[excellent]}')

print(f'\n 재수강 대상 ({np.sum(failing)}명):')
print(f'이름 : {names[failing]}')
print(f'점수 : {scores[failing]}')

high_scores : [ True False  True False  True False  True  True False  True]
80점 이상인 학생 : 
점수 : [85 95 88 92 84 90]
이름 : ['김철수' '박민수' '정우진' '오준석' '윤서연' '송하윤']
excellent : [False False  True False False False  True False False  True]
failing : [False False False  True False False False False False False]

 우수 학생 (3명):
이름 : ['박민수' '오준석' '송하윤']
점수 : [95 92 90]

 재수강 대상 (1명):
이름 : ['최지연']
점수 : [68]


##### 고급 필터링

In [ ]:
# 1차원 배열
a = np.arange(10,20)
print(f'a={a}')
print(f'a < 15: {np.where(a < 15)}')

# 2차원 배열
arr = np.array([[1,6,3],
                [7,2,9],
                [4,8,5]])

cond = np.where(arr > 4)    # cond : 튜플
print(f'arr>4 : {cond}')
# 반환된 인덱스를 이용해 원소 접근
element = arr[cond]
print(element)

a=[10 11 12 13 14 15 16 17 18 19]
a < 15: (array([0, 1, 2, 3, 4]),)
arr>4 : (array([0, 1, 1, 2, 2]), array([1, 0, 2, 1, 2]))
[6 7 9 8 5]


##### 고급 필터링 예제

In [3]:
# 학생별 과목 점수     (수학, 영어, 과학)
student_scores = np.array([[85,90,78],    # 학생1
                            [72,85,88],    # 학생2
                            [95,92,94],    # 학생3
                            [68,75,70],    # 학생4
                            [88,82,90]])    # 학생5
subjects = ['수학', '영어','과학']

# 학생별 평균 점수 계산
avg_scores=  np.mean(student_scores, axis=1)
print('학생별 평균 점수 :')

for i, avg in enumerate(avg_scores):
    print(f'학생{i+1}: {avg:.1f}점')

# 모든 과목에서 80점 이상인 학생
all_above_80 = np.all(student_scores > 80, axis=1)

print(f'all_above_80 : {all_above_80}')
print(np.where(all_above_80))

# np.where(조건)[0] : 조건을 만족하는 행의 index를 리턴
print(f'\n모든 과목 80점 이상 : 학생  {np.where(all_above_80)[0]}')

# 수학 과목에서 90점 이상인 학생
math_excellent = student_scores[:,0] >= 90
print(np.where(math_excellent))
print(f'수학 90점 이상 학생 : {np.where(math_excellent)[0]}')

학생별 평균 점수 :
학생1: 84.3점
학생2: 81.7점
학생3: 93.7점
학생4: 71.0점
학생5: 86.7점
all_above_80 : [False False  True False  True]
(array([2, 4]),)

모든 과목 80점 이상 : 학생  [2 4]
(array([2]),)
수학 90점 이상 학생 : [2]
