# Numpy 과제 #1
### KDT 12기 이재헌
#### 4명의 학생과 4개의 과목의 성적 데이터 분석

In [1]:
import numpy as np

subjects = np.array(['수학', '영어', '과학', '사회'])
student_data = np.array([
    ['김철수', 90, 85, 78, 92],
    ['이영희', 76, 80, 79, 85],
    ['박민수', 88, 92, 91, 86],
    ['최지연', 70, 75, 80, 85],
])

##### * 학생 이름과 점수를 분리하여 아래와 같이 화면에 출력

In [2]:
names = student_data[:,0]
scores = np.array(student_data[:,1:], dtype='int32')
print(f'학생 이름:{names}')
print('점수 데이터:')
print(f'{scores}')

학생 이름:['김철수' '이영희' '박민수' '최지연']
점수 데이터:
[[90 85 78 92]
 [76 80 79 85]
 [88 92 91 86]
 [70 75 80 85]]


##### * 과목별 평균을 계산하고 가장 평균이 높은 과목을 화면에 출력

In [86]:
avg_scores = np.mean(scores, axis=0)
print('과목별 평균 점수')
for i, avg in enumerate(avg_scores):
    print(f'{subjects[i]} : {avg:.1f}점')

high_avg = np.max(avg_scores)
high_sub = subjects[np.argmax(avg_scores)]
print()
print(f'평균이 가장 높은 과목 : {high_sub} ({high_avg}점)')

과목별 평균 점수
수학 : 81.0점
영어 : 83.0점
과학 : 82.0점
사회 : 87.0점

평균이 가장 높은 과목 : 사회 (87.0점)


##### * 학생별 총점과 평균을 계산하고 총점이 가장 높은 학생의 이름 및 총점 출력

In [118]:
print('학생별 성적')
for i, avg in enumerate(scores):
    print(f'{names[i]} : 총점 {np.sum(scores[i])}점, 평균 {np.mean(scores[i]):.1f}점')

total = np.sum(scores, axis=1)
high_total = np.max(total)
high_student = names[np.argmax(total)]
mean = np.mean(scores, axis=1)
high_mean = np.max(mean)
print()
print(f'1등 학생 : {high_student} (총점 : {high_total}점, 평균 : {high_mean:.1f}점)')

학생별 성적
김철수 : 총점 345점, 평균 86.2점
이영희 : 총점 320점, 평균 80.0점
박민수 : 총점 357점, 평균 89.2점
최지연 : 총점 310점, 평균 77.5점

1등 학생 : 박민수 (총점 : 357점, 평균 : 89.2점)


##### * 각 과목별 80점 이상인 점수 찾기(Boolean indexing)

In [46]:
above80 = scores >= 80
print('80점 이상 과목 :')
print(f'{above80}')

80점 이상 과목 :
[[ True  True False  True]
 [False  True False  True]
 [ True  True  True  True]
 [False False  True  True]]


##### * 학생별 80점 이상인 과목의 수 출력

In [128]:
count_over80 = np.sum(above80, axis=1)
print('학생별 80점 이상 과목 수 :')
for i in range(len(names)):
    print(f'{names[i]} : {count_over80[i]}과목')

학생별 80점 이상 과목 수 :
김철수 : 3과목
이영희 : 2과목
박민수 : 4과목
최지연 : 2과목


##### * 모든 과목의 점수가 80점 이상인 학생 출력 및 수학 과목이 90점인 학생 이름 출력

In [60]:
all_above_80 = np.all(scores >= 80, axis=1)
math_over_90 = scores[:, 0] >= 90
student_high = np.where(all_above_80)[0]
student_math = np.where(math_over_90)[0]
print('모든 과목이 80점 이상인 학생 :', names[student_high][0])
print('수학 90점 이상인 학생 :', names[student_math][0])

모든 과목이 80점 이상인 학생 : 박민수
수학 90점 이상인 학생 : 김철수


##### * 전체 점수 통계(전체 평균, 최고점수, 최저점수, 표준편차 계산)

In [64]:
print('=== 전체 점수 통계 ===')
print(f'전체 평균 : {np.mean(scores):.1f}점')
print(f'최고 점수 : {np.max(scores)}점')
print(f'최저 점수 : {np.min(scores)}점')
print(f'표준편차 : {np.std(scores):.1f}점')

=== 전체 점수 통계 ===
전체 평균 : 83.2점
최고 점수 : 92점
최저 점수 : 70점
표준편차 : 6.4점


##### * 학생 별 최고/최저 점수 과목 출력

In [134]:
high_score_sub = np.max(scores, axis=0)
min_score_sub = np.min(scores, axis=0)
high_score_stu = np.max(scores, axis=1)
min_score_stu = np.min(scores, axis=1)
print('=== 학생별 최고/최저 과목 ===')
for i in range(len(names)):
    print(names[i])
    print(f'   최고 점수 : {high_score_stu[i]}점')
    print(f'   최저 점수 : {min_score_stu[i]}점')

=== 학생별 최고/최저 과목 ===
김철수
   최고 점수 : 92점
   최저 점수 : 78점
이영희
   최고 점수 : 85점
   최저 점수 : 76점
박민수
   최고 점수 : 92점
   최저 점수 : 86점
최지연
   최고 점수 : 85점
   최저 점수 : 70점


##### * 과목별 점수 분포 출력(최고 점수, 최저 점수, 점수 차이(최고점수-최저점수)

In [136]:
print('=== 과목별 점수 분포 ===')
for i in range(len(subjects)):
    print(f'{subjects[i]}: 최고 : {high_score_sub[i]}점, 최저 : {min_score_sub[i]}점, 점수차이 : {high_score_sub[i] - min_score_sub[i]}점')

=== 과목별 점수 분포 ===
수학: 최고 : 90점, 최저 : 70점, 점수차이 : 20점
영어: 최고 : 92점, 최저 : 75점, 점수차이 : 17점
과학: 최고 : 91점, 최저 : 78점, 점수차이 : 13점
사회: 최고 : 92점, 최저 : 85점, 점수차이 : 7점
